# version: '3.8'

services:
  # Ваш quiz-service
  quiz-service:
    build:
      context: .  
      dockerfile: quiz-service/Dockerfile
    ports:
      - "5000:80"   # Прокси порта API (можно изменить на другой)
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=db;Database=QuizService;User=sa;Password=Password123;TrustServerCertificate=True;
    networks:
      - imbaquiz-net
    restart: always

  # База данных SQL Server
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123
    ports:
      - "1433:1433"
    networks:
      - imbaquiz-net
    volumes:
      - mssql_data:/var/opt/mssql
    restart: always

  # Дополнительные сервисы, например, RabbitMQ
  # rabbitmq:
  #   image: "rabbitmq:management"
  #   ports:
  #     - "15672:15672"  # Для доступа к RabbitMQ через браузер
  #     - "5672:5672"    # Для работы с очередями
  #   networks:
  #     - imbaquiz-net
  #   restart: always

# Настройки сети
networks:
  imbaquiz-net:
    driver: bridge

# Монтируем том для сохранения данных SQL Server
volumes:
  mssql_data:
